#this file is for app engine
service: backend-service
runtime: python37
entrypoint: gunicorn -b :$PORT application:application
handlers:
- url: /.*  # This regex directs all routes to main.app
  script: auto


